# Generated by Django 4.1.6 on 2023-03-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("url", models.URLField(blank=True, max_length=255, unique=True)),
                ("host", models.CharField(blank=True, max_length=200)),
                ("displayName", models.CharField(blank=True, max_length=200)),
                ("github", models.URLField(blank=True, max_length=255, null=True)),
                (
                    "profileImage",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["displayName"],
            },
        ),
    ]
