# Generated by Django 4.1.6 on 2023-03-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowedRemotes",
            fields=[
                (
                    "username",
                    models.CharField(
                        max_length=10, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("password", models.CharField(max_length=10)),
            ],
        ),
    ]
