# Generated by Django 4.1.6 on 2023-04-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0002_alter_follow_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='actor',
            field=models.URLField(),
        ),
    ]
