# Generated by Django 4.1.6 on 2023-03-27 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Inbox",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("url", models.URLField(blank=True)),
                ("source", models.CharField(blank=True, max_length=50)),
                ("origin", models.CharField(blank=True, max_length=50)),
                ("contentType", models.CharField(blank=True, max_length=20)),
                (
                    "author_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
