# Generated by Django 4.1.6 on 2023-03-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inbox",
            name="origin",
        ),
        migrations.RemoveField(
            model_name="inbox",
            name="source",
        ),
        migrations.AddField(
            model_name="inbox",
            name="sender",
            field=models.URLField(
                default="http://localhost:8000/api/authors/dummy", max_length=512
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="inbox",
            name="summary",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="inbox",
            name="url",
            field=models.URLField(max_length=512),
        ),
    ]
