# Generated by Django 4.1.6 on 2023-03-27 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("inbox", "0002_remove_inbox_origin_remove_inbox_source_inbox_sender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inbox",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
