<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-03-22 17:11
=======
# Generated by Django 4.1.6 on 2023-03-24 17:47
>>>>>>> dev

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Post',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('origin', models.CharField(blank=True, max_length=50)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('contentType', models.CharField(blank=True, choices=[('text/markdown', 'text/markdown'), ('plain/Text', 'plain/Text')], max_length=20)),
                ('categories', models.JSONField(blank=True, default=apps.posts.models.Post.category_template)),
                ('comments', models.JSONField(blank=True, default=apps.posts.models.Post.commentlist_template, verbose_name='comment')),
                ('count', models.PositiveBigIntegerField(default=0)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.BooleanField(choices=[(True, 'PUBLIC'), (False, 'PRIVATE')], default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('unlisted', models.BooleanField(blank=True, default=False)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('dateTime', models.DateTimeField(auto_now_add=True)),
                ('followers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='authors.author')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='authors.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=250)),
                ('host', models.CharField(blank=True, max_length=100)),
                ('displayName', models.CharField(max_length=200)),
                ('profileImage', models.ImageField(blank=True, upload_to='')),
                ('parent_comment_id', models.BigIntegerField(blank=True, null=True)),
                ('parent_post_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
=======
            name="Post",
            fields=[
                (
                    "id",
                    models.URLField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("source", models.CharField(blank=True, max_length=256, null=True)),
                ("origin", models.CharField(blank=True, max_length=256, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "contentType",
                    models.CharField(
                        choices=[
                            ("text/plain", "text/plain"),
                            ("text/markdown", "text/markdown"),
                            ("application/base64", "application/base64"),
                            ("image/png;base64", "image/png;base64"),
                            ("image/jpeg;base64", "image/jpeg;base64"),
                        ],
                        default="text/plain",
                        max_length=20,
                    ),
                ),
                ("content", models.CharField(max_length=1000)),
                (
                    "categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=20),
                        blank=True,
                        size=None,
                    ),
                ),
                ("published", models.DateTimeField(auto_now_add=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PUBLIC", "PUBLIC"), ("PRIVATE", "PRIVATE")],
                        default="PUBLIC",
                        max_length=10,
                    ),
                ),
                ("unlisted", models.BooleanField(blank=True, default=False)),
                (
                    "author_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
>>>>>>> dev
            ],
            options={
                "ordering": ["published"],
            },
        ),
    ]
