# Generated by Django 4.1.5 on 2023-04-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='52042f6b-cebb-4301-bf05-55500256f41c', editable=False, max_length=256, primary_key=True, serialize=False),
        ),
    ]
