# Generated by Django 4.1.6 on 2023-04-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='c4c8ca59-7cb0-49f5-92bd-b8b0e74b100b', editable=False, max_length=256, primary_key=True, serialize=False),
        ),
    ]
