# Generated by Django 4.1.6 on 2023-04-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_alter_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.CharField(
                default="fbca98c4-f590-48f7-b809-ed8f625d267d",
                editable=False,
                max_length=256,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
