# Generated by Django 4.1.5 on 2023-04-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='aacf2fd0-a207-4c74-937c-1558de7137e4', editable=False, max_length=256, primary_key=True, serialize=False),
        ),
    ]
