# Generated by Django 4.1.5 on 2023-04-02 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='b8e6dd34-ea94-46ee-a782-d08c41a57346', editable=False, max_length=256, primary_key=True, serialize=False),
        ),
    ]
