# Generated by Django 4.1.6 on 2023-04-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='1551bc31-7764-4ac0-b237-5de79491599b', editable=False, max_length=256, primary_key=True, serialize=False),
        ),
    ]
