# Generated by Django 4.1.5 on 2023-03-30 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='0d0bd03f-88b0-498e-8496-f8c71065d347', editable=False, max_length=256, primary_key=True, serialize=False),
        ),
    ]
