# Generated by Django 4.1.6 on 2023-03-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0010_alter_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.CharField(
                default="41c7ca20-c565-4d47-b104-8cf137fa6256",
                editable=False,
                max_length=256,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
