# Generated by Django 4.1.6 on 2023-03-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0011_alter_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.CharField(
                default="e273e097-085d-4f4d-89ca-ea0a4e65b49f",
                editable=False,
                max_length=256,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
