# Generated by Django 4.1.6 on 2023-04-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0012_alter_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.CharField(
                default="06711556-1d95-45a5-971f-5203537306a3",
                editable=False,
                max_length=256,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
