# Generated by Django 4.1.6 on 2023-04-01 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0013_alter_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.CharField(
                default="ba8708fb-13d3-4ce8-a75d-537c2cf80ddb",
                editable=False,
                max_length=256,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
