# Generated by Django 4.1.6 on 2023-04-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0013_alter_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="id",
            field=models.CharField(
                default="d0895415-032c-43ca-bc72-6358fcb39175",
                editable=False,
                max_length=256,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
