# Generated by Django 4.1.5 on 2023-04-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='26e1d71a-1282-4278-951f-3b62d7d48fec', editable=False, max_length=256, primary_key=True, serialize=False),
        ),
    ]
