# Generated by Django 4.1.5 on 2023-04-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='feeceb03-39a3-415b-9b38-916246b45150', editable=False, max_length=256, primary_key=True, serialize=False),
        ),
    ]
