# Generated by Django 4.1.5 on 2023-04-01 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='9ec38a6e-5584-47c8-9c1b-9dd353d54c91', editable=False, max_length=256, primary_key=True, serialize=False),
        ),
    ]
