# Generated by Django 4.1.5 on 2023-04-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='805b6e38-548e-49a0-8ca3-8954192b9188', editable=False, max_length=256, primary_key=True, serialize=False),
        ),
    ]
