# Generated by Django 4.1.5 on 2023-04-01 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='474b72e5-5d8d-4ea0-bb89-1232cf0ca2b7', editable=False, max_length=256, primary_key=True, serialize=False),
        ),
    ]
